# Generated by Django 4.1.5 on 2023-09-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_issue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='actions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
    ]
