# Generated by Django 4.2.5 on 2023-10-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_issue_assigned_user_issue_resolved_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('IN PROGRESS', 'in progress'), ('RESOLVED', 'resolved'), ('CONFIRMED', 'confirmed')], default='NEW', max_length=11),
        ),
    ]
